language: java

jdk:
  - openjdk8

install: true

before_script:
  # Configure Sonatype OSSRH credentials (encrypted)
  - sed -i 's/ossrhUsername=/ossrhUsername='ossrhUsername'/g' gradle.properties
  - sed -i 's/ossrhUsername=/ossrhPassword='ossrhUsername'/g' gradle.properties

script:
  gradle test
