language: java

jdk:
  - openjdk8

install: true

before_script:
  - echo ${GPG_KEY} | base64 -d > publish_key.gpg
  - gpg --quiet --batch --yes --decrypt --passphrase="${SIGNING_PASSWORD}" --output secret.gpg publish_key.gpg

  - echo signing.keyId=${SIGNING_KEY_ID} > gradle.properties
  - echo signing.password=${SIGNING_PASSWORD} >> gradle.properties
  - echo signing.secretKeyRingFile=secret.gpg >> gradle.properties

  - echo ossrhUsername=${ossrhUsername} >> gradle.properties
  - echo ossrhPassword=${ossrhPassword} >> gradle.properties

script:
  gradle --info test

after_success:
  - gradle --info jacocoTestReport
  - bash <(curl -s https://codecov.io/bash)

after_script:
  - rm gradle.properties || true
  - rm publish_key.gpg || true
  - rm secret.gpg || true
