language: java

jdk:
  - openjdk8

install: true

before_script:
  # Configure Sonatype OSSRH credentials (encrypted)
  - sed -i.bak "s/ossrhUsername=/ossrhUsername=${ossrhUsername}/g" gradle.properties && rm gradle.properties.bak
  - sed -i.bak "s/ossrhPassword=/ossrhPassword=${ossrhPassword}/g" gradle.properties && rm gradle.properties.bak
  - echo ${GPG_KEY} | base64 -d > publish_key.gpg
  - gpg --quiet --batch --yes --decrypt --passphrase="${SIGNING_PASSWORD}" \
    --output secret.gpg publish_key.gpg
  - echo signing.keyId=${SIGNING_KEY_ID}
  - echo signing.password=${SIGNING_PASSWORD}
  - echo signing.secretKeyRingFile=publish_key.gpg

script:
  gradle --info test

after_success:
  - gradle --info jacocoTestReport
  - bash <(curl -s https://codecov.io/bash)
